### ISSUE TITLE
Unknown interaction - No Discord.Interactions.ComponentCommandInfo found for 1_0

### ISSUE THREAD

**Issue by BlyZeDev** [d4n3436/Fergun.Interactive#35] opened 2024-11-24 15:22 UTC
The paginator is displayed properly but if I interact with any button I get this:
`No Discord.Interactions.ComponentCommandInfo found for 1_0` -> 1_0 can be 2_4 or 0_1 so I guess it's just the button id.
Delete Button works even though I get `No Discord.Interactions.ComponentCommandInfo found for 1_0` as well.
But when I try to use the arrow buttons to paginate I get `No Discord.Interactions.ComponentCommandInfo found for 1_0` as well as the StackTrace below.

**Startup**
```cs
.AddSingleton(new InteractiveConfig
{
    LogLevel = IsDebug() ? LogSeverity.Debug : LogSeverity.Info,
    ReturnAfterSendingPaginator = true
})
```

**Command**
```cs
await DeferAsync(true);

var player = await GetPlayerAsync(false);
if (player is null) return;

await _interactive.SendPaginatorAsync(
    MobyPaginators.GetQueue(player.Queue.Count, player.CurrentItem!, player.Queue),
    Context.Interaction, TimeSpan.FromSeconds(30), InteractionResponseType.DeferredUpdateMessage, true, null, true);
```

**The paginator**
```cs
return new LazyPaginatorBuilder()
    .WithActionOnCancellation(ActionOnStop.DeleteMessage)
    .WithActionOnTimeout(ActionOnStop.DisableInput)
    .WithCacheLoadedPages(true)
    .WithDeletion(DeletionOptions.Invalid)
    .WithFooter(PaginatorFooter.PageNumber)
    .WithInputType(InputType.Buttons)
    .WithMaxPageIndex((int)Math.Ceiling(count / (double)ItemsPerPage) - 1)
    .WithPageFactory((index) =>
    {
        var sb = new StringBuilder();

        if (index == 0) sb.AppendLine($"**Now playing:** {(current.Reference.IsPresent ? current.Track!.Title : current.Identifier)}");

        var currentTrackCount = index * ItemsPerPage;
        foreach (var item in queue.Skip(index * ItemsPerPage).Take(ItemsPerPage))
        {
            currentTrackCount++;
            sb.AppendLine($"**{currentTrackCount}:** {(item.Reference.IsPresent ? item.Track!.Title : item.Identifier)}");
        }

        sb.Length--;

        return new PageBuilder()
            .WithColor(MobyCore.BaseColor)
            .WithTitle(@"**\🎼 Queue**")
            .WithDescription(sb.ToString());
    })
    .AddOption(new PaginatorButton("◀️", PaginatorAction.Backward, ButtonStyle.Primary))
    .AddOption(new PaginatorButton("▶️", PaginatorAction.Forward, ButtonStyle.Primary))
    .AddOption(new PaginatorButton("❌", PaginatorAction.Exit, ButtonStyle.Danger))
    .Build();
```

**StackTrace**
```
Error: Failed to execute interaction callback (message Id: 1310262618426052680) | Source: InteractiveService
Exception: Discord.Net.HttpException: The server responded with error 10062: Unknown interaction
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.WebSocket.SocketMessageComponent.UpdateAsync(Action`1 func, RequestOptions options)
   at Fergun.Interactive.Pagination.Paginator.TryUpdateMessageAsync(Func`3 updateMethod, Int32 previousPageIndex, Boolean includeComponents)
   at Fergun.Interactive.Pagination.Paginator.HandleInteractionAsync(SocketMessageComponent input, IUserMessage message)
   at Fergun.Interactive.Pagination.PaginatorCallback.ExecuteAsync(SocketInteraction interaction)
   at Fergun.Interactive.InteractiveService.<>c__DisplayClass52_0.<<InteractionCreated>b__0>d.MoveNext()
```

**Comment by d4n3436** [comment] 2024-11-24 17:08
Duplicate of #7.
There's a new method to check if an interaction is meant for `InteractiveService` so you can just add this inside of your interaction handler:

```c#
private async Task HandleInteractionAsync(SocketInteraction interaction)
{
    if (_interactive.IsManaged(interaction))
        return;
}
```

**Closed by d4n3436** 2024-11-24 17:08 UTC
Labels: duplicate
