### ISSUE TITLE
Failed to execute interaction callback

### ISSUE THREAD

**Issue by vinaghost** [d4n3436/Fergun.Interactive#23] opened 2023-01-31 03:57 UTC
The different in my project with your sample project is mine has Discord.Interactions.InteractionService instead of CommandService

My InteractionCreated 
```cs
private async Task InteractionCreated(SocketInteraction interaction)
{
    try
    {
       
        var context = new SocketInteractionContext(Client, interaction);
        await _interactionService.ExecuteCommandAsync(context, _provider);
    }
    catch (Exception exception)
    {
        Logger.LogError(exception, "Exception occurred whilst attempting to handle interaction.");
    }
}
```

InteractionExecuted
```cs
private async Task InteractionExecuted(ICommandInfo command, IInteractionContext context, IResult result)
{
    if (result.IsSuccess)
        return;

    // Handle error execution result here.
    var embed = new EmbedBuilder()
        .WithTitle("Error!")
        .WithDescription(result.ErrorReason)
        .WithColor(Color.Red)
        .Build();

    await context.Interaction.RespondAsync(embed: embed);
}
```

Log message:
```
[ERR] Fergun.Interactive.InteractiveService
 InteractiveService: Failed to execute interaction callback (message Id: 1069827449770229790)
Discord.Net.HttpException: The server responded with error 40060: Interaction has already been acknowledged.
   at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
   at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
   at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
   at Discord.API.DiscordRestApiClient.SendJsonAsync(String method, String endpoint, Object payload, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
   at Discord.API.DiscordRestApiClient.CreateInteractionResponseAsync(InteractionResponse response, UInt64 interactionId, String interactionToken, RequestOptions options)
   at Discord.Rest.InteractionHelper.SendInteractionResponseAsync(BaseDiscordClient client, InteractionResponse response, IDiscordInteraction interaction, IMessageChannel channel, RequestOptions options)
   at Discord.WebSocket.SocketMessageComponent.UpdateAsync(Action`1 func, RequestOptions options)
   at Fergun.Interactive.Pagination.Paginator.HandleInteractionAsync(SocketMessageComponent input, IUserMessage message)
   at Fergun.Interactive.Pagination.PaginatorCallback.ExecuteAsync(SocketInteraction interaction)
   at Fergun.Interactive.InteractiveService.<>c__DisplayClass50_0.<<InteractionCreated>b__0>d.MoveNext()
```

Any advise?

**Comment by d4n3436** [comment] 2023-01-31 05:34
Duplicate of #7, you have to avoid responding to interactions meant for `InteractiveService`, check the code in issue to solve the problem.

**Closed by d4n3436** 2023-01-31 05:34 UTC
Labels: duplicate

**Comment by vinaghost** [comment] 2023-01-31 07:27
for anyone found this

```cs
private async Task InteractionCreated(SocketInteraction interaction)
{
    if (interaction is SocketMessageComponent messageComponent && _interactiveService.Callbacks.ContainsKey(messageComponent.Message.Id))
    {
        return;
    }
    try
    {
        var context = new SocketInteractionContext(Client, interaction);
        await _interactionService.ExecuteCommandAsync(context, _provider);
    }
    catch (Exception exception)
    {
        Logger.LogError(exception, "Exception occurred whilst attempting to handle interaction.");
    }
}```
